config/routes.rb
Rails.application.routes.draw do

  root 'book_apps#index'
  resources :book_apps

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_app.rb
class BookApp < ApplicationRecord
    validates :title, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_apps_controller.rb
class BookAppsController < ApplicationController
  before_action :set_book_app, only: %i[ show edit update destroy ]

  # GET /book_apps or /book_apps.json
  def index
    @book_apps = BookApp.all
  end

  # GET /book_apps/1 or /book_apps/1.json
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /book_apps/new
  def new
    @book_app = BookApp.new
    respond_to do |format|
      format.js
    end  
  end

  # GET /book_apps/1/edit
  def edit
    respond_to do |format|
      format.js
    end     
  end

  # POST /book_apps or /book_apps.json
  def create
    @book_app = BookApp.create(book_app_params)

    respond_to do |format|
      format.js
    end
  end

  # PATCH/PUT /book_apps/1 or /book_apps/1.json
  def update
    respond_to do |format|
      if @book_app.update(book_app_params)
        format.js
      else
        format.js
      end
    end
  end

  # DELETE /book_apps/1 or /book_apps/1.json
  def destroy
    @book_app.destroy

    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_app
      @book_app = BookApp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_app_params
      params.require(:book_app).permit(:title, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_apps_helper.rb
module BookAppsHelper
end

app/views/book_apps/_book.html.erb
<tr id="<%= book_app.id %>">
  <td style="text-align:center"><%= book_app.title %></td>
  <td style="text-align:center"><%= book_app.price %></td>
  <td style="text-align:center"><%= link_to 'Show', book_app, remote: true, class:"btn btn-info"%></td>
  <td style="text-align:center"><%= link_to 'Edit', edit_book_app_path(book_app), remote: true, class:"btn btn-warning
    " %></td>
  <td style="text-align:center"><%= link_to 'Destroy', book_app, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class:"btn btn-dark" %></td>
</tr>

app/views/book_apps/_book_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h1 class="modal-title fs-5" id="exampleModalLabel"><%= model_title %></h1>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      <div id="error"></div>
        <% if params[:action] == 'show' %>     
          <p>
            <strong>Title:</strong>
            <%= @book_app.title %>
          </p>

          <p>
            <strong>Price:</strong>
            <%= @book_app.price %>
          </p> 
        <% else %>
          <%= render 'book_model', book_app: @book_app %>
        <% end %>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    </div>
  </div>
</div>   

app/views/book_apps/_book_model.html.erb
<%= form_with(model: book_app, remote: true) do |form| %>
  <div style="margin-top:14px" class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_apps/_error.html.erb
<% if book_app.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(book_app.errors.count, "error") %> Prohibited this book from
        being saved</h2>
        
        <ul>
        <% @book_app.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>      

app/views/book_apps/create.js.erb
<% if @book_app.errors.any? %>
  $('#error').html("<%= j render 'error', book_app: @book_app %>")

<% else %>
  $('.bookTab').append("<%= j render 'book', book_app: @book_app, model_title: 'create new book'%>");
  $('#book-content').modal('hide');
<% end %>  

app/views/book_apps/destroy.js.erb
$("#<%= @book_app.id %>").remove();

app/views/book_apps/edit.js.erb
$('#book-content').html("<%= j render 'book_form', book_app: @book_app, model_title: 'Update Book' %>");
$('#book-content').modal('show');

app/views/book_apps/index.html.erb
<p id="notice"><%= notice %></p>

<b><h1 class='text-center'>Books</h1></b><br>
<center>
  <table class="table table-striped table-hover" style="width:1000px">
    <thead>
      <tr style="border:1px solid black; background-color:skyblue">
        <th class='kuch-bhi' scope="col">Title</th>
        <th class='kuch-bhi' scope="col">Price</th>
        <th colspan="3" style="text-align:center">Actions</th>
      </tr>
    </thead>

    <tbody class="bookTab">
      <% @book_apps.each do |book_app| %>
        <%= render 'book', book_app: book_app %> 
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Book App', new_book_app_path, remote: true %> 
</center>

app/views/book_apps/new.js.erb
$('#book-content').html("<%= j render 'book_form', book_app: @book_app, model_title: 'Create new Book' %>");
$('#book-content').modal('show');

app/views/book_apps/show.js.erb
$('#book-content').html("<%= j render 'book_form', book_app: @book_app, model_title: 'Show Book' %>");
$('#book-content').modal('show');

app/views/book_apps/update.js.erb
<% if @book_app.errors.any? %>
  $('#error').html("<%= j render 'error', book_app: @book_app %>")

<% else %>
  $('#book-content').modal('hide');
  $("#<%= @book_app.id %>").replaceWith("<%= j render 'book', book_app: @book_app %>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
    <div class="modal fade" id="book-content" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
  </body>
</html>